include ../Makefile.tests_common

BOARD_WHITELIST += native nrf52dk

USEPKG += mbed-crypto

CFLAGS += -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function

include $(RIOTBASE)/Makefile.include